/**
 * FF Tank MCP Server
 * Exposes FF Tank Supabase data as MCP tools for Claude Code.
 * Runs on VPS alongside the OpenClaw bridge.
 * Port: 3002
 */

require('dotenv').config();
const http = require('http');

const SB_BASE = (process.env.SUPABASE_URL || '').replace(/\/$/, '');
const SB_KEY  = process.env.SUPABASE_ANON_KEY || '';
const SB_H    = { 'Content-Type': 'application/json', 'apikey': SB_KEY, 'Authorization': `Bearer ${SB_KEY}` };
const PORT    = process.env.MCP_PORT || 3002;

async function sb(path) {
  const r = await fetch(`${SB_BASE}/rest/v1/${path}`, { headers: SB_H });
  return r.json();
}

// ─── Tool definitions ────────────────────────────────────────────────────────
const TOOLS = [
  {
    name: 'get_opportunities',
    description: 'Fetch opportunities from FF Tank. Filter by status (new, contacted, qualified, closed) or signal (rfp, market, venue, competitor). Sorted by score descending.',
    inputSchema: {
      type: 'object',
      properties: {
        status:  { type: 'string', enum: ['new', 'contacted', 'qualified', 'closed'], description: 'Filter by status' },
        signal:  { type: 'string', enum: ['rfp', 'market', 'venue', 'competitor'], description: 'Filter by signal type' },
        limit:   { type: 'number', description: 'Max records to return (default 20)' },
      },
    },
  },
  {
    name: 'get_contacts',
    description: 'Fetch contacts (outreach drafts with contact info) from FF Tank.',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', description: 'Max records (default 50)' },
      },
    },
  },
  {
    name: 'get_outreach_drafts',
    description: 'Fetch outreach email drafts generated by FF Tank agents.',
    inputSchema: {
      type: 'object',
      properties: {
        limit: { type: 'number', description: 'Max records (default 20)' },
      },
    },
  },
  {
    name: 'get_job_runs',
    description: 'Fetch recent OpenClaw job run history — status, duration, cost.',
    inputSchema: {
      type: 'object',
      properties: {
        status: { type: 'string', enum: ['running', 'completed', 'failed'], description: 'Filter by status' },
        limit:  { type: 'number', description: 'Max records (default 20)' },
      },
    },
  },
  {
    name: 'get_weekly_brief',
    description: 'Fetch the most recent Fatfish weekly intelligence brief.',
    inputSchema: { type: 'object', properties: {} },
  },
  {
    name: 'get_target_accounts',
    description: 'Fetch target accounts being tracked by FF Tank scout.',
    inputSchema: {
      type: 'object',
      properties: {
        status: { type: 'string', enum: ['active', 'paused'], description: 'Filter by status' },
      },
    },
  },
];

// ─── Tool execution ───────────────────────────────────────────────────────────
async function runTool(name, args) {
  const limit = args.limit || 20;
  switch (name) {
    case 'get_opportunities': {
      let q = `opportunities?order=overall_score.desc.nullslast&limit=${limit}&select=id,title,company,signal,status,overall_score,fit_score,why_this_matters,recommended_next_step,created_at`;
      if (args.status) q += `&status=eq.${args.status}`;
      if (args.signal) q += `&signal=eq.${args.signal}`;
      return sb(q);
    }
    case 'get_contacts': {
      return sb(`outreach_drafts?order=created_at.desc&limit=${args.limit || 50}&select=id,company,contact_name,contact_email,contact_linkedin,subject,created_at`);
    }
    case 'get_outreach_drafts': {
      return sb(`outreach_drafts?order=created_at.desc&limit=${limit}&select=*`);
    }
    case 'get_job_runs': {
      let q = `job_runs?order=created_at.desc&limit=${limit}&select=id,job_name,status,duration_ms,estimated_cost,result_summary,error_message,created_at`;
      if (args.status) q += `&status=eq.${args.status}`;
      return sb(q);
    }
    case 'get_weekly_brief': {
      return sb(`weekly_briefs?order=generated_at.desc&limit=1`);
    }
    case 'get_target_accounts': {
      let q = `target_accounts?order=created_at.desc&limit=50`;
      if (args.status) q += `&status=eq.${args.status}`;
      return sb(q);
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

// ─── MCP JSON-RPC handler ─────────────────────────────────────────────────────
async function handleRPC(body) {
  const { id, method, params } = body;

  if (method === 'initialize') {
    return { jsonrpc: '2.0', id, result: {
      protocolVersion: '2024-11-05',
      serverInfo: { name: 'ff-tank-mcp', version: '1.0.0' },
      capabilities: { tools: {} },
    }};
  }

  if (method === 'tools/list') {
    return { jsonrpc: '2.0', id, result: { tools: TOOLS } };
  }

  if (method === 'tools/call') {
    const { name, arguments: args } = params;
    try {
      const data = await runTool(name, args || {});
      return { jsonrpc: '2.0', id, result: {
        content: [{ type: 'text', text: JSON.stringify(data, null, 2) }],
      }};
    } catch (e) {
      return { jsonrpc: '2.0', id, error: { code: -32000, message: e.message } };
    }
  }

  return { jsonrpc: '2.0', id, error: { code: -32601, message: 'Method not found' } };
}

// ─── HTTP server ──────────────────────────────────────────────────────────────
const server = http.createServer(async (req, res) => {
  if (req.method !== 'POST') {
    res.writeHead(405); res.end();
    return;
  }
  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', async () => {
    try {
      const parsed = JSON.parse(body);
      const response = await handleRPC(parsed);
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(response));
    } catch (e) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32700, message: 'Parse error' } }));
    }
  });
});

server.listen(PORT, '127.0.0.1', () => {
  console.log(`[ff-tank-mcp] MCP server listening on 127.0.0.1:${PORT}`);
});
